[channels.stable.plugins.Accountant]
built_commit = "7cce41d485d4a95447691de437cd6723e619c817"
time_built = 2024-04-15T16:10:43.441
effective_version = "1.4.0.0"
[channels.stable.plugins.Accountant.changelogs."1.4.0.0"]
time_released = 2024-04-15T16:10:43.441
changelog = "Update for KR"
[channels.stable.plugins.EmoteLog]
built_commit = "92028d445f734a51a3470339498d1687ee776327"
time_built = 2024-04-14T13:55:04.187
effective_version = "1.1.2.0"
[channels.stable.plugins.EmoteLog.changelogs."1.1.2.0"]
time_released = 2024-04-14T13:55:04.187
changelog = "Track who used what emotes on you."
[channels.stable.plugins.Hunty]
built_commit = "88b3f987bd2e447c1aa55e830e889f3187e73850"
time_built = 2024-04-14T15:13:55.591
effective_version = "1.3.0.1"
[channels.stable.plugins.Hunty.changelogs."1.3.0.1"]
time_released = 2024-04-14T15:13:55.591
changelog = "Update for KR"
[channels.stable.plugins.ChillFrames]
built_commit = "e7cb4d212de16978dbc7a9a9f5ac345b6950dbdd"
time_built = 2024-04-14T16:15:56.038
effective_version = "2.1.1.3"
[channels.stable.plugins.ChillFrames.changelogs."2.1.1.3"]
time_released = 2024-04-14T16:15:56.038
changelog = "Update for KR"
[channels.stable.plugins.GatherBuddy]
built_commit = "eb9f2ceca5dbc7b3d12a844f311cafeb695e0612"
time_built = 2024-04-15T09:32:13.769
effective_version = "3.3.2.3"
[channels.stable.plugins.GatherBuddy.changelogs."3.3.2.3"]
time_released = 2024-04-15T09:32:13.769
changelog = "Update for KR"
[channels.stable.plugins.Distance]
built_commit = "80e541ecef38555b7a5d2860ffb797a4f98b3b7f"
time_built = 2024-04-15T12:35:16.469
effective_version = "1.1.1.2"
[channels.stable.plugins.Distance.changelogs."1.1.1.2"]
time_released = 2024-04-15T12:35:16.469
changelog = "Update for KR"
[channels.stable.plugins.DeviceChangeFix]
built_commit = "4c468b79156bd21ca147130410f90cc891a95ddd"
time_built = 2024-04-15T13:55:09.136
effective_version = "2.0.3.0"
[channels.stable.plugins.DeviceChangeFix.changelogs."2.0.3.0"]
time_released = 2024-04-15T13:55:09.136
changelog = "Update for KR"
[channels.stable.plugins.ActionTimeline]
built_commit = "9c3df56537445f62a6bd3bd205f195eea739ea61"
time_built = 2024-04-15T16:23:36.944
effective_version = "1.3.0.1"
[channels.stable.plugins.ActionTimeline.changelogs."1.3.0.1"]
time_released = 2024-04-15T16:23:36.944
changelog = "Update for KR"
[channels.stable.plugins.BDTHPlugin]
built_commit = "7f0e44e39997a852f51dada3f0c2f4cd16c848eb"
time_built = 2024-04-15T16:47:49.900
effective_version = "1.6.2.0"
[channels.stable.plugins.BDTHPlugin.changelogs."1.6.2.0"]
time_released = 2024-04-15T16:47:49.900
changelog = "Update for KR"
[channels.testing-live.plugins.AetherCompass]
built_commit = "d66f1c86e65e31925dbb51d88598822619d0e19b"
time_built = 2023-01-18T16:19:10.716
effective_version = "1.6.2.2"
[channels.testing-live.plugins.AetherCompass.changelogs."1.5.0.4"]
time_released = 2022-09-02T15:54:43.896
changelog = "New compass for Island Sanctuary (testing)"
[channels.testing-live.plugins.AetherCompass.changelogs."1.5.1.0"]
time_released = 2022-09-03T12:26:09.357
changelog = "- New compass for Island Sanctuary (testing)\n- Update to configuration loading\n"
[channels.testing-live.plugins.AetherCompass.changelogs."1.5.2.0"]
time_released = 2022-09-30T15:15:03.392
changelog = "- Fix config loading issue (Thanks to Caraxi)\n"
[channels.testing-live.plugins.AetherCompass.changelogs."1.6.2.2"]
time_released = 2023-01-18T16:19:10.716
changelog = "Patch 6.3 Update\n\n- New compass Eureka Elementals for detecting elementals in Eureka (by apetih)\n- Other minor update and bug fixes to Island Sanctuary Compass\n"
[channels.testing-net6.plugins]
