[channels.stable.plugins.Accountant]
built_commit = "7cce41d485d4a95447691de437cd6723e619c817"
time_built = 2024-04-15T16:10:43.441
effective_version = "1.4.0.0"
[channels.stable.plugins.Accountant.changelogs."1.4.0.0"]
time_released = 2024-04-15T16:10:43.441
changelog = "Update for KR"
[channels.stable.plugins.EmoteLog]
built_commit = "92028d445f734a51a3470339498d1687ee776327"
time_built = 2024-04-14T13:55:04.187
effective_version = "1.1.2.0"
[channels.stable.plugins.EmoteLog.changelogs."1.1.2.0"]
time_released = 2024-04-14T13:55:04.187
changelog = "Track who used what emotes on you."
[channels.stable.plugins.Hunty]
built_commit = "88b3f987bd2e447c1aa55e830e889f3187e73850"
time_built = 2024-04-14T15:13:55.591
effective_version = "1.3.0.1"
[channels.stable.plugins.Hunty.changelogs."1.3.0.1"]
time_released = 2024-04-14T15:13:55.591
changelog = "Update for KR"
[channels.stable.plugins.ChillFrames]
built_commit = "e7cb4d212de16978dbc7a9a9f5ac345b6950dbdd"
time_built = 2024-04-14T16:15:56.038
effective_version = "2.1.1.3"
[channels.stable.plugins.ChillFrames.changelogs."2.1.1.3"]
time_released = 2024-04-14T16:15:56.038
changelog = "Update for KR"
[channels.stable.plugins.GatherBuddy]
built_commit = "eb9f2ceca5dbc7b3d12a844f311cafeb695e0612"
time_built = 2024-04-15T09:32:13.769
effective_version = "3.3.2.3"
[channels.stable.plugins.GatherBuddy.changelogs."3.3.2.3"]
time_released = 2024-04-15T09:32:13.769
changelog = "Update for KR"
[channels.stable.plugins.Distance]
built_commit = "80e541ecef38555b7a5d2860ffb797a4f98b3b7f"
time_built = 2024-04-15T12:35:16.469
effective_version = "1.1.1.2"
[channels.stable.plugins.Distance.changelogs."1.1.1.2"]
time_released = 2024-04-15T12:35:16.469
changelog = "Update for KR"
[channels.stable.plugins.DeviceChangeFix]
built_commit = "4c468b79156bd21ca147130410f90cc891a95ddd"
time_built = 2024-04-15T13:55:09.136
effective_version = "2.0.3.0"
[channels.stable.plugins.DeviceChangeFix.changelogs."2.0.3.0"]
time_released = 2024-04-15T13:55:09.136
changelog = "Update for KR"
[channels.stable.plugins.ActionTimeline]
built_commit = "9c3df56537445f62a6bd3bd205f195eea739ea61"
time_built = 2024-04-15T16:23:36.944
effective_version = "1.3.0.1"
[channels.stable.plugins.ActionTimeline.changelogs."1.3.0.1"]
time_released = 2024-04-15T16:23:36.944
changelog = "Update for KR"
[channels.stable.plugins.PriceInsight]
built_commit = "cebc13328364c95a3ef5505305906f273326027f"
time_built = 2024-04-16T08:18:25.428
effective_version = "2.8.0.0"
[channels.stable.plugins.PriceInsight.changelogs."2.8.0.0"]
time_released = 2024-04-16T08:18:25.428
changelog = "- Rewrote caching logic to better avoid unnecessary requests to universalis\n- Improved tooltip display when \"Always display NQ and HQ\" is turned off\n"
[channels.stable.plugins.BigPlayerDebuffs]
built_commit = "e80426ed7afae1e147500acdc1be2fde2fe1b2e3"
time_built = 2024-04-15T17:49:34.149
effective_version = "1.1.0.9"
[channels.stable.plugins.BigPlayerDebuffs.changelogs."1.1.0.9"]
time_released = 2024-04-15T17:49:34.149
changelog = "Update for KR"
[channels.stable.plugins.DailyDuty]
built_commit = "3e8f0c8b4f41107ef65d43681634c876335822ec"
time_built = 2024-04-15T18:50:13.989
effective_version = "4.0.6.1"
[channels.stable.plugins.DailyDuty.changelogs."4.0.6.1"]
time_released = 2024-04-15T18:50:13.989
changelog = "Update for KR"
[channels.stable.plugins."Dalamud.DiscordBridge"]
built_commit = "a8a592c5eb591b6bce25fb8e0c2860ebb6696af1"
time_built = 2024-04-15T18:55:36.099
effective_version = "1.4.4.0"
[channels.stable.plugins."Dalamud.DiscordBridge".changelogs."1.4.4.0"]
time_released = 2024-04-15T18:55:36.099
changelog = "Update for KR"
[channels.stable.plugins."Dalamud.FullscreenCutscenes"]
built_commit = "6191823fd2d5666c1f2d5a94a5ee245c5b88f144"
time_built = 2024-04-15T19:01:04.720
effective_version = "1.0.0.2"
[channels.stable.plugins."Dalamud.FullscreenCutscenes".changelogs."1.0.0.2"]
time_released = 2024-04-15T19:01:04.720
changelog = "Update for KR"
[channels.stable.plugins."Dalamud.RichPresence"]
built_commit = "6abfdd7a8973061162fb607e202649dd3e1f2c1c"
time_built = 2024-04-15T19:01:10.792
effective_version = "2.0.3.0"
[channels.stable.plugins."Dalamud.RichPresence".changelogs."2.0.3.0"]
time_released = 2024-04-15T19:01:10.792
changelog = "Update for KR"
[channels.stable.plugins.DamageInfoPlugin]
built_commit = "e83a31ba1bd5cef7375517a51b2069c5c6ba9f4c"
time_built = 2024-04-15T19:08:21.292
effective_version = "2.3.0.3"
[channels.stable.plugins.DamageInfoPlugin.changelogs."2.3.0.3"]
time_released = 2024-04-15T19:08:21.292
changelog = "Update for KR"
[channels.stable.plugins.VFXEditor]
built_commit = "acdaf8a9232a101fab87586f530ae13c5f79a359"
time_built = 2024-04-15T19:08:43.668
effective_version = "1.8.3.3"
[channels.stable.plugins.VFXEditor.changelogs."1.8.3.3"]
time_released = 2024-04-15T19:08:43.668
changelog = "Update for KR"
[channels.stable.plugins.FauxHollowsSolver]
built_commit = "5a26a6e619ed58e3658a0db541a2471e2180eb02"
time_built = 2024-04-16T08:04:09.730
effective_version = "1.3.0.0"
[channels.stable.plugins.FauxHollowsSolver.changelogs]
[channels.stable.plugins.EngageTimer]
built_commit = "f5bfa07a4ca0be31623ad687926124a50251d019"
time_built = 2024-04-16T08:04:16.639
effective_version = "2.3.2.0"
[channels.stable.plugins.EngageTimer.changelogs."2.3.2.0"]
time_released = 2024-04-16T08:04:16.639
changelog = "- Add an option to draw the custom 0-5 numbers without hiding the original countdown\n- Make animation match vanilla a bit better\n"
[channels.stable.plugins.FantasyPlayer]
built_commit = "d08a6911953037f7fefe3d113993d2da54b9627f"
time_built = 2024-04-16T08:04:27.709
effective_version = "2.2.0.2"
[channels.stable.plugins.FantasyPlayer.changelogs."2.2.0.2"]
time_released = 2024-04-16T08:04:27.709
changelog = "**Bug Fixes**\n- Fixes so that the plugin disposes properly\n- The browser should now open using the same method Dalamud uses for logging in, Linux/Mac OSX users see if you can login now\n"
[channels.stable.plugins.MiniCactpotSolver]
built_commit = "0764fcc25b49fff26da45638640f46c33d9ed50c"
time_built = 2024-04-16T08:04:32.237
effective_version = "1.3.0.3"
[channels.stable.plugins.MiniCactpotSolver.changelogs]
[channels.stable.plugins.EnmityHp]
built_commit = "2c495026819e3411069eb94b0ed0dd2a3a58eae5"
time_built = 2024-04-16T08:04:36.570
effective_version = "2.0.1.1"
[channels.stable.plugins.EnmityHp.changelogs]
[channels.stable.plugins.EnemyListDebuffs]
built_commit = "77a9c25fa0f516281fbc265cfb97157ef7d7aeb3"
time_built = 2024-04-16T08:04:40.912
effective_version = "0.3.9.0"
[channels.stable.plugins.EnemyListDebuffs.changelogs."0.3.9.0"]
time_released = 2024-04-16T08:04:40.912
changelog = "Update for KR"
[channels.testing-live.plugins.AetherCompass]
built_commit = "d66f1c86e65e31925dbb51d88598822619d0e19b"
time_built = 2023-01-18T16:19:10.716
effective_version = "1.6.2.2"
[channels.testing-live.plugins.AetherCompass.changelogs."1.5.0.4"]
time_released = 2022-09-02T15:54:43.896
changelog = "New compass for Island Sanctuary (testing)"
[channels.testing-live.plugins.AetherCompass.changelogs."1.5.1.0"]
time_released = 2022-09-03T12:26:09.357
changelog = "- New compass for Island Sanctuary (testing)\n- Update to configuration loading\n"
[channels.testing-live.plugins.AetherCompass.changelogs."1.5.2.0"]
time_released = 2022-09-30T15:15:03.392
changelog = "- Fix config loading issue (Thanks to Caraxi)\n"
[channels.testing-live.plugins.AetherCompass.changelogs."1.6.2.2"]
time_released = 2023-01-18T16:19:10.716
changelog = "Patch 6.3 Update\n\n- New compass Eureka Elementals for detecting elementals in Eureka (by apetih)\n- Other minor update and bug fixes to Island Sanctuary Compass\n"
[channels.testing-net6.plugins]
